export type SeedSpirit = {
  name: string;
  category: string;
  container_size?: number;
  aliases?: string[];
};

/** Top 100 spirits commonly stocked in bar/restaurant inventory. */
export const TOP_100_SPIRITS: SeedSpirit[] = [
  { name: 'Absolut Vodka', category: 'vodka' },
  { name: 'Belvedere', category: 'vodka', aliases: ['Bel', 'Bellvedere'] },
  { name: 'Grey Goose', category: 'vodka' },
  { name: 'Ketel One', category: 'vodka' },
  { name: "Tito's Handmade Vodka", category: 'vodka', aliases: ['Titos'] },
  { name: 'Smirnoff', category: 'vodka' },
  { name: 'Stolichnaya', category: 'vodka', aliases: ['Stoli'] },
  { name: 'Chopin', category: 'vodka' },
  { name: 'Russian Standard', category: 'vodka' },
  { name: 'Finlandia', category: 'vodka' },
  { name: 'Tanqueray', category: 'gin', aliases: ['Tankeray'] },
  { name: 'Bombay Sapphire', category: 'gin', aliases: ['Bombay'] },
  { name: "Hendrick's Gin", category: 'gin', aliases: ['Hendricks'] },
  { name: 'Beefeater', category: 'gin' },
  { name: 'Aviation American Gin', category: 'gin', aliases: ['Aviation'] },
  { name: 'The Botanist', category: 'gin' },
  { name: 'Plymouth Gin', category: 'gin' },
  { name: 'Monkey 47', category: 'gin' },
  { name: 'Roku Gin', category: 'gin' },
  { name: 'Sipsmith London Dry Gin', category: 'gin', aliases: ['Sipsmith'] },
  { name: 'Jameson', category: 'whiskey' },
  { name: "Jack Daniel's", category: 'whiskey', aliases: ['Jack Daniels'] },
  { name: "Maker's Mark", category: 'whiskey', aliases: ['Makers Mark'] },
  { name: 'Woodford Reserve', category: 'whiskey' },
  { name: 'Bulleit Bourbon', category: 'whiskey', aliases: ['Bulleit'] },
  { name: 'Knob Creek', category: 'whiskey' },
  { name: 'Buffalo Trace', category: 'whiskey' },
  { name: 'Wild Turkey 101', category: 'whiskey', aliases: ['Wild Turkey'] },
  { name: 'Four Roses', category: 'whiskey' },
  { name: 'Johnnie Walker Red Label', category: 'scotch', aliases: ['Johnnie Red'] },
  { name: 'Johnnie Walker Black Label', category: 'scotch', aliases: ['Johnnie Black'] },
  { name: 'Chivas Regal 12', category: 'scotch', aliases: ['Chivas'] },
  { name: 'Macallan 12', category: 'scotch', aliases: ['Macallan'] },
  { name: 'Glenfiddich 12', category: 'scotch' },
  { name: 'Glenlivet 12', category: 'scotch' },
  { name: 'Crown Royal', category: 'whiskey' },
  { name: 'Jim Beam', category: 'whiskey' },
  { name: 'Evan Williams', category: 'whiskey' },
  { name: "Basil Hayden's", category: 'whiskey', aliases: ['Basil Haydens'] },
  { name: "Angel's Envy", category: 'whiskey', aliases: ['Angels Envy'] },
  { name: 'Bacardi Superior', category: 'rum', aliases: ['Bacardi'] },
  { name: 'Captain Morgan Spiced Rum', category: 'rum', aliases: ['Captain Morgan'] },
  { name: 'Malibu', category: 'rum' },
  { name: 'Mount Gay Eclipse', category: 'rum', aliases: ['Mount Gay'] },
  { name: 'Appleton Estate', category: 'rum' },
  { name: 'Plantation 3 Stars', category: 'rum', aliases: ['Plantation'] },
  { name: 'Diplomatico Reserva', category: 'rum', aliases: ['Diplomatico'] },
  { name: "Myers's Dark Rum", category: 'rum', aliases: ['Myers'] },
  { name: 'Kraken Black Spiced Rum', category: 'rum', aliases: ['Kraken'] },
  { name: 'Goslings Black Seal', category: 'rum', aliases: ['Goslings'] },
  { name: 'Patron Silver', category: 'tequila', aliases: ['Patron'] },
  { name: 'Don Julio Blanco', category: 'tequila', aliases: ['Don Julio'] },
  { name: 'Casamigos Blanco', category: 'tequila', aliases: ['Casamigos'] },
  { name: '1800 Silver', category: 'tequila' },
  { name: 'Jose Cuervo Especial', category: 'tequila', aliases: ['Cuervo'] },
  { name: 'Espolon Blanco', category: 'tequila', aliases: ['Espolon'] },
  { name: 'Herradura Silver', category: 'tequila' },
  { name: 'Milagro Silver', category: 'tequila' },
  { name: 'Ocho Plata', category: 'tequila' },
  { name: 'El Jimador Blanco', category: 'tequila', aliases: ['Jimador'] },
  { name: 'Del Maguey Vida Mezcal', category: 'mezcal', aliases: ['Vida Mezcal'] },
  { name: 'Montelobos Mezcal', category: 'mezcal', aliases: ['Montelobos'] },
  { name: 'Ilegal Mezcal', category: 'mezcal' },
  { name: 'Baileys Irish Cream', category: 'liqueur', aliases: ['Baileys'] },
  { name: 'Kahlua', category: 'liqueur' },
  { name: 'Grand Marnier', category: 'liqueur' },
  { name: 'Cointreau', category: 'liqueur' },
  { name: 'DeKuyper Triple Sec', category: 'liqueur', aliases: ['Triple Sec'] },
  { name: 'Disaronno Amaretto', category: 'liqueur', aliases: ['Amaretto', 'Disaronno'] },
  { name: 'Campari', category: 'liqueur' },
  { name: 'Aperol', category: 'liqueur' },
  { name: 'St-Germain', category: 'liqueur', aliases: ['St Germain'] },
  { name: 'Chartreuse Green', category: 'liqueur', aliases: ['Green Chartreuse'] },
  { name: 'Chartreuse Yellow', category: 'liqueur', aliases: ['Yellow Chartreuse'] },
  { name: 'Drambuie', category: 'liqueur' },
  { name: 'Frangelico', category: 'liqueur' },
  { name: 'Midori', category: 'liqueur' },
  { name: 'Chambord', category: 'liqueur' },
  { name: 'Benedictine', category: 'liqueur' },
  { name: 'Luxardo Maraschino', category: 'liqueur', aliases: ['Maraschino'] },
  { name: 'Averna', category: 'liqueur' },
  { name: 'Fernet-Branca', category: 'liqueur', aliases: ['Fernet'] },
  { name: 'Jägermeister', category: 'liqueur', aliases: ['Jager', 'Jagermeister'] },
  { name: 'Sambuca', category: 'liqueur' },
  { name: 'Fireball Cinnamon Whisky', category: 'liqueur', aliases: ['Fireball'] },
  { name: 'Hennessy VS', category: 'cognac', aliases: ['Hennessy'] },
  { name: 'Rémy Martin VSOP', category: 'cognac', aliases: ['Remy Martin'] },
  { name: 'Courvoisier VS', category: 'cognac' },
  { name: 'Martell VS', category: 'cognac' },
  { name: 'Dolin Rouge Vermouth', category: 'vermouth', aliases: ['Dolin Rouge'] },
  { name: 'Carpano Antica Formula', category: 'vermouth', aliases: ['Carpano'] },
  { name: 'Martini Rosso', category: 'vermouth' },
  { name: 'Martini Extra Dry', category: 'vermouth' },
  { name: 'Lillet Blanc', category: 'aperitif' },
  { name: "Pimm's No. 1", category: 'liqueur', aliases: ['Pimms'] },
  { name: 'Angostura Bitters', category: 'bitters' },
  { name: "Peychaud's Bitters", category: 'bitters', aliases: ['Peychauds'] },
  { name: 'Underberg', category: 'bitters' },
  { name: 'Velvet Falernum', category: 'liqueur', aliases: ['Falernum'] },
  { name: 'Pama Pomegranate Liqueur', category: 'liqueur', aliases: ['Pama'] },
];
